### PR TITLE
add formatting tools and format all the things

### PR DESCRIPTION
**Pull request by ryanatkn**
This updates Prettier to v2, upgrades to the latest Gro version that adds formatting, sets the line width to 100, adds a formatting check to CI, and formats all existing files. The noise is all isolated to the second commit, and the rest are small.

The CI command currently [uses the full path to the Gro CLI](https://github.com/feltcoop/felt/pull/24/commits/8815d64f7f759a97818bd1f53ed7da3ab4f36c19#diff-42c92e55465a3edde413334753e1c2e9R27), `node_modules/.bin/gro`. I'm not sure of the best way to do that and my googling is failing me.

### CODE REVIEW

**Comment by greatbacon** [comment]
Gradle uses a wrapper shell script (`./gradlew`) to get around the binary not necessarily being sourced to the environment namespace. I wouldn't call it a blocker to this PR, but googling "gradle wrapper" might give you some inspiration for future work.

**Comment by greatbacon** [comment]
Which I literally just realized, follow that convention would be the gro wrapper would be `./grow` 😁

**Comment by greatbacon** [comment]
Here's the official gradle doc page on the wrapper https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by ryanatkn** [comment]
Awesome thanks for the link, I'll read through this soon.

**Pull request merged**
