### PR TITLE
Changed the emoji used in the voluntary page

### PR DESCRIPTION
**Pull request by trusttri**
Changed the emoji used in the voluntary consentful and unconsentful pages to ✨. Added a new status to Message called "inform" for this. Might end up changing the emoji to something else if people find it confusing.

# Pull Request 💚-🐑👁️

In order to help us easily visualize & review components, please consider putting a [Svelte REPL](https://svelte.dev/repl) example below:
<REPL link goes here>

### CODE REVIEW

**Review by greatbacon — APPROVED** [review]
looks good to me! Although I think you need to run `gro clean` to get the formatting check to run and pass the test runner

**Comment by trusttri** [comment]
Oh I see, thank you for letting me know! Should I run that command on my terminal and do something else...? 
Was wondering if there's anything I need to do on GitHub to pass the checks.

**Comment by ryanatkn** [comment]
Thank you!

For formatting you can run `gro format` (or `npx gro format` if you don't have it installed globally). If you're using VSCode the Prettier extension will take care of it -- you may need to set `"editor.formatOnSave": true,`.

**Comment by trusttri** [comment]
Gotcha, thank you! That's super helpful to know.

**Pull request merged**
