### PR TITLE
remove postcss and tailwindcss and strip styles

### PR DESCRIPTION
**Pull request by ryanatkn**
This removes PostCSS and TailwindCSS. They're currently incompatible with ES modules and it's not the CSS solution we wanted long term anyway. They were useful for the mockup but we'll use something else going forward.

This PR leaves the app styles in a broken state. Not to be deployed!

The next PR will convert Felt to using ES modules.

Happily, this cuts our dependencies in half. Removing all of these dependencies revealed that we implicitly relied on the `fs-extra` transitive dependency, hence the update to `server.ts`.

### CODE REVIEW

**Comment by ryanatkn** [comment]
Oh yeah about that.. There's been a battle waging in my head about whether or not we should use Tailwind-style CSS classes or normal CSS, either plain or with a preprocessor like SCSS.

If we choose the former, ~90% of that code will stay the same. (but not via Tailwind for reasons too big for this discussion)

If we choose the latter, it'll be helpful to directly convert those existing classes and `@apply` calls to CSS.

I agree that all that commented code is uncool and complaint-worthy. So are the dead classes throughout the markup.

Of course, we could work off the historical version of these files when we do real styling. So we don't need make a mess now to save a lot of time. Removing both the commented code and CSS classes is an option.

Which of these would you prefer?

1. leave things as they are in this commit (I don't think either of us prefer this)
2. remove just the commented code
3. replace just the commented code with real styles (probably using placeholder CSS variables)
4. remove both the commented code and dead classes
5. replace both the commented code and dead classes with real styles

---

Here's a summary of where I'm at right now on styling. There are a lot of implications here and I don't feel like I have all of the important information yet. But I also don't want to devote the time to figure out what I need to know, not yet.

The primary concerns off the top of my head:

- what does runtime theming look like?
- what's the styling interface we expose to users? what can we do here that gives as much power as possible to users without exposing component internals? (the nightmare scenario is where component classes and markup structure are relied upon by user styles)
- what are the performance characteristics?
- what is the dev authoring experience like?

The second one is really important and the most fuzzy for me right now.

**Comment by greatbacon** [comment]
I think that since we both recognize that styling is important, but not something that we are currently willing/able to give the space and consideration to (as the current focus is more on core functionality) my two cents would be #4.) remove both the commented code and dead classes. I also think the initial prototype has served its purpose, and at this point I think it will be more beneficial to us to be working from as close to a blank slate as possible.

**Comment by ryanatkn** [comment]
Sounds good to me. I'll update this PR with the changes.

I'll probably add some plain CSS just to un-break the layout, but otherwise keep it minimal.

**Comment by ryanatkn** [comment]
Phew that feels good. I feel like there's something else I meant to do, will wait a bit before marking it as ready.

**Comment by ryanatkn** [comment]
Was thinking of some stuff that's more appropriate in later PRs. Also we may want to do a very quick pass over some pieces to make them less ugly, but this is good for now IMO.

**Comment by ryanatkn** [comment]
😆

**Pull request merged**
